version: '3'
services:
  quarkushop:
#    image: quarkus/quarkushop:latest
    image: kalilmvp/quarkushop-monolithic-application:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql-db:5432/demo
    ports:
      - 8080:8080
    depends_on:
      - postgresql-db
  postgresql-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
